\encoding UTF8
drop table if exists order_book;
drop table if exists orders;
drop table if exists requests;
drop table if exists users;
drop table if exists books;

create table books (
 id int generated by default as identity primary key,
 name text not null,
 description text,
 author text not null,
 genre text not null,
 price numeric(10,2) not null check (price >= 0),
 status varchar(20) not null,
 publish_year integer not null,
 stock_date date
);

create table users (
 id int generated by default as identity primary key,
 name text unique not null,
 password text not null,
 role varchar(10) not null
 check (role in ('ADMIN', 'USER'))
);

create table orders (
 id int generated by default as identity primary key,
 user_id integer not null references users(id),
 created_at date not null,
 completed_at date,
 status varchar(20) not null
);

create table order_book (
 order_id integer not null references orders(id) on delete cascade,
 book_id integer not null references books(id),
 quantity integer not null check (quantity > 0),
 primary key (order_id, book_id)
);

create table requests (
 id int generated by default as identity primary key,
 created_at date not null,
 book_id integer not null references books(id),
 quantity integer not null check (quantity > 0)
);

