create table books (
    id int generated by default as identity primary key,
    name text not null,
    description text,
    author text not null,
    genre text not null,
    price numeric(10,2) not null check (price >= 0),
    status varchar(20) not null,
    publish_year integer not null,
    stock_date date
);