create table users (
    id int generated by default as identity primary key,
    name text unique not null,
    password text not null,
    role varchar(10) not null
    check (role in ('ADMIN', 'USER'))
);