create table orders (
     id int generated by default as identity primary key,
     user_id integer not null references users(id),
     created_at date not null,
     completed_at date,
     status varchar(20) not null
);