create table requests (
   id int generated by default as identity primary key,
   created_at date not null,
   book_id integer not null references books(id),
   quantity integer not null check (quantity > 0)
);